import Head from "next/head";
import Navbar from "../components/Navbar";
import Sidebar from "../components/Sidebar";
import TopPopular from "./TopPopular";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-300">
        <Navbar />

        <div className="flex">
          <Sidebar />
          <TopPopular />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
